### ISSUE TITLE
Date format for time entry doesn't match docs

### ISSUE THREAD

**Issue by bglase** [getroadmap/roadmap-api#1]
The docs say {start} and {end} are in YYMMDD format.
GET v1.0/project/{projectId}/timeentry/{start}/{end}

https://api.ppmroadmap.com/v1.0/project/593286/timeentry/140601/140630
results in a 500 error for me, while
https://api.ppmroadmap.com/v1.0/project/593286/timeentry/20140601/20140630
seems to work as expected.  

I think the format is really YYYYMMDD

**Comment by davejclausen** [comment]
@bglase, thanks for being our first issue-reporter!

Yes, this is a typo in the docs.  We'll get this corrected.

Thanks again.

**Comment by IgorBurakov** [comment]
Documentation is corrected
