### ISSUE TITLE
Unable to update or delete records

### ISSUE THREAD

**Issue by bglase** [getroadmap/roadmap-api#2]
Current API does not seem to give the ability to update or delete records (for instance, to delete a time entry once it has been made, or update the ResourceCode for a specific user).  It seems generally that only adding things is supported at this time.
The interface will probably need to handle update/delete if it is to be used generally to sync with other applications.

**Comment by davejclausen** [comment]
@bglase, you are very right.  Deletes and Updates will come in a future release - I will try to get a timeframe for you.

**Comment by IgorBurakov** [comment]
All CRUD functions are available since version 1.1:
https://api.ppmroadmap.com/Help/Ver?ver=Ver1_1
