### ISSUE TITLE
timeentry add does not accept a rate

### ISSUE THREAD

**Issue by bglase** [getroadmap/roadmap-api#3]
Posting {"ProjectID":593126,"ResourceID":663665,"Date":"2014-08-03","Time":" 4.00 ","Description":"Imported worklog","Rate":87.6,"RoleId":114805,"TodoItemID":12442111}

returns a 200 status, with 
{
  "ID": 2244667,
  "ProjectID": 593126,
  "ProjectName": "Takata MSB Controller",
  "ProjectCustomCode": "14CS02",
  "ProjectCode": "14CS02",
  "MilestoneID": null,
  "TodoItemID": 12442111,
  "ResourceID": 663665,
  "ResourceName": "Tanya O'Connor",
  "ResourceCustomCode": "O'CONNOR, TANYA",
  "ResourceCode": "O'CONNOR, TANYA",
  "RoleID": 114805,
  "RoleName": "Program Manager",
  "Date": "2014-08-03T00:00:00",
  "Time": 4.0,
  "Description": "Imported worklog",
  "Rate": 111.6800
}

I was hoping the posted rate would appear in the 'adj rate' column of the time entry.

**Comment by bkingbking** [comment]
@bglase Rates are applied globally at the role level (std rate).  It can be overridden at the project level (i.e. adj rate).  For example, suppose Bill is an Account Manager, and the standard rate for Account Managers is $100.
- If Bill logs 10h against any project, that will yield $1,000
- However, suppose Bill has an adjustable rate of $90 for Project ABC, that will yield $900.  Thus, adjusted rates is exceptions based.

Here's a [summary](https://ppmroadmap.uservoice.com/knowledgebase/articles/347828-billable-rates-and-project-budget) of how it works from our support pages.

@davejclausen Please step in if the API is expected to behave differently than the UX layer.

**Comment by bglase** [comment]
Got it, thanks.  Makes sense, just wasn't what I was hoping.  I can work with it.
The tracking of project 'actuals' is relatively basic in Roadmap - if it were to be enhanced, I'd suggest allowing actual rates to be overridden on a timeentry, and also a way to track non-labor (e.g. material costs) like a budget against actuals.

**Comment by bkingbking** [comment]
@bglase Thanks for the feedback.  Will have to think this one through because a lot of clients would go bonkers if we allowed users to adjust rates on a per time-entry basis.  They don't always want resources to know their billing rate, let alone give them the option to get it wrong!  

Our product roadmap includes support for non-labor costs, as well as the ability to flag individual tasks as non-billable.

**Comment by bglase** [comment]
Right - I suppose overriding the rate would only be useful for syncing (e.g. loading) entries from another system, through the REST API for instance
