### ISSUE TITLE
CORS Headers?

### ISSUE THREAD

**Issue by mmealling** [getroadmap/roadmap-api#4]
Are there any plans to add CORS headers to the API?

**Comment by bkingbking** [comment]
Guys - Updating this issue to keep the correspondence in a single, reference-able location:

> @mmealling Does the API support CORS headers or are you guys assuming this will be accessed by some server side app that proxies the requests?
> 
> @davejclausen The development team is open to supporting CORS.  We want to do a bit of vetting from a security standpoint, as well as an effort analysis -- which we'll then share with Roadmap's management team and go from there.  The workaround for CORS of course is for you to develop server-side "wrapper" methods ... your javascript would call the wrapper methods and the wrapper methods would call the Roadmap API.  Yet I know this is extra work.  :) Let us start this eval / estimate; and we'll keep this dialog running.
> 
> @mmealling Understood. I assumed I was going to have to proxy it through a server to get the stuff I needed for our executive dashboard. If the CORS headers were there I could simply stick the assets in an S3 bucket and forgo the server side. No rush, just knowing its on the roadmap is sufficient. CORS aside, does the server support JSONP for GET?

**Comment by DmitryLapshov** [comment]
@mmealling CORS headers have been added.
