### ISSUE TITLE
Implementations for various programming languages

### ISSUE THREAD

**Issue by schmunk42** [getroadmap/roadmap-api#6]
Are there already implementations for clients for the Roadmap API, eg. for PHP?

**Comment by davejclausen** [comment]
Thanks for this question.

At this time, we are investing all of our energy into the API itself -- trying to make it as solid and usable as possible.

We'd be utterly thrilled if some programmers in the Roadmap community (using various platforms) would share-out the libraries they've written to consume our API.

Yet it's something we wouldn't be averse to providing ourselves, in the future.

p.s. If by chance you need to make Roadmap talk to another SaaS system, we have a suite of www.zapier.com triggers and actions that are in public-beta.  You can go to https://ppmroadmap.uservoice.com, hit Contact, and request access to this public-beta.

**Comment by bkingbking** [comment]
Hi Tobias -- FYI, there are some JavaScript examples in `PublicAPI\Test` folder.

**Comment by schmunk42** [comment]
> Hi Tobias -- FYI, there are some JavaScript examples in PublicAPI\Test folder.

Sorry, which repo?

**Comment by bkingbking** [comment]
https://github.com/bkingbking/Roadmap/tree/master/PublicAPI/Test
