### ISSUE TITLE
Empty resource returned

### ISSUE THREAD

**Issue by matwolff** [getroadmap/roadmap-api#7]
When accessing /project/{projectID}/resource I am receiving an empty array vs the resources that are displayed in our roadmap acct.

**Comment by bkingbking** [comment]
@matwolff Apologies for the delayed response (some cross wires internally).  One of our developers will respond to you shortly.

@davejclausen @AndrewKaplanovsky

**Comment by davejclausen** [comment]
Hi matwolff,

The request you mention "gets the resources assigned to a project at the **project-level**" (see also https://api.ppmroadmap.com/Help/Api/GET-v1.1-project-projectId-resource).

This help article explains what we mean by "project-level" resources: https://ppmroadmap.uservoice.com/knowledgebase/articles/261453

I'm guessing that what you're looking for is a listing of all resources assigned to any work item in the project.  Our API presently doesn't support this as a direct request - as we feel this is more of a "reporting function" that one would use the Roadmap app itself for.  (The main intent of the API is to get raw data in and out between systems.)  Yet let us know if you have a difference of opinion here. :)

Also, let us know if this reply helped.  Thanks.

**Comment by bkingbking** [comment]
@matwolff As discussed in the (separate) help ticket sent by Russell, we will add a method to support your use case in the near future.

**Comment by benkutil** [comment]
for histories sake, find below the updated endpoints:
- https://api.ppmroadmap.com/Help/Api/GET-v1.2-project-projectId-resource-all
- https://api.ppmroadmap.com/Help/Api/GET-v1.2-resource-resourceId-work-item-wiType_projectID
- https://api.ppmroadmap.com/Help/Api/GET-v1.2-resource-resourceId-work-item-wiType-completed_projectID
